export const SUPPORTED_LOCALES = ["es", "en"] as const;
export type Locale = (typeof SUPPORTED_LOCALES)[number];
export const LOCALE_COOKIE = "neora_locale";

const messages = {
  en: {
    accessDenied: "Access denied", noRole: "Your identity does not have an application role.", marketExplorer: "Market Explorer", noScores: "No licensed market scores are available for this account.",
    intelligence: "Internal market intelligence", marketOverview: "Market overview", subtitle: "Prioritize markets for deeper research with traceable evidence.", city: "City", pilot: "Pilot · Colombia", language: "Language", english: "English", spanish: "Spanish",
    topOpportunity: "Top opportunity", averageOpportunity: "Average opportunity", evidenceConfidence: "Evidence confidence", evaluatedSectors: "Evaluated sectors", noScoredSectors: "No scored sectors", acrossScored: "Across scored sectors", separate: "Separate from opportunity", insufficientData: "with insufficient data",
    licensePending: "License review pending", syntheticWarning: "Synthetic sample only. It cannot be published into actionable lead views or used as official market evidence.", importStatus: "Import status", rowsAccepted: "rows accepted", noRecentRun: "No recent run", run: "Run",
    signals: "Read the two signals independently", signalsDetail: "Opportunity expresses relative research priority. Confidence expresses evidence quality; neither is a probability of purchase or expected revenue.", period: "Period", researchPriority: "Research priority", sectorRanking: "Sector ranking", selectSector: "Select a sector to inspect the evidence behind its score.", sectors: "sectors", sector: "Sector", opportunity: "Opportunity", confidence: "Confidence", readyForReview: "Ready for review", selectedSector: "Selected sector", factorEvidence: "Factor evidence", evidence: "Evidence", confidenceEvidence: "Confidence evidence", evidenceRecords: "Evidence records", openSource: "Open source", observed: "Observed", license: "license", review: "review", missing: "Missing", points: "pts", outOf100: "/ 100", evidencePanel: "Selected sector evidence", confidenceModel: "Confidence model", model: "Model", home: "Neora Labs home", footer: "Synthetic decision-support preview · Scores are deterministic, versioned, and not production evidence.", overview: "Overview", ranking: "Ranking", navEvidence: "Evidence", primary: "Primary", selectedEvidence: "Selected sector evidence", workspace: "Internal research workspace",
    back: "Back to explorer", importOfficial: "Import official source", importDescription: "Data is uploaded directly to private storage, retained by checksum, and reviewed before a separate worker processes it. It is not used to score companies.", source: "Source", requiredCiiu: "Required CIIU", localFile: "Local file", version: "Version", dictionaryLabels: "EMICRON dictionary labels (JSON)", dictionaryHelp: "Every Pxxxx variable used must have its official label; codes without one are not interpreted.", protections: "Active protections", checksum: "SHA-256 calculated in the browser.", immutablePath: "Immutable raw/sha256/… path.", separateReviewer: "The same identity cannot approve.", unresolvedMapping: "ICA data without a verified mapping remains insufficient evidence.", preparing: "Preparing upload…", uploadReview: "Upload and request review", recentRequests: "Recent requests", noRequests: "No upload requests yet.", file: "File", status: "Status", rule: "Rule", chooseFile: "Choose a file before continuing.", invalidJson: "Dictionary labels must be valid JSON.", uploadPrepareError: "Could not prepare the upload", storageMissing: "S3 storage is not configured yet. No file was uploaded.", uploadRejected: "The direct upload was rejected; the file was not sent for review.", confirmError: "Could not confirm the upload", received: "File received. It is pending review by a second authorized identity.", unexpectedError: "Unexpected error", ciiuNotice: "Required classification: Rev. 4 A.C. (2022).", emicronNotice: "EMICRON only produces contextual GRUPOS12 evidence; it does not create division scores.", icaNotice: "ICA remains blocked until each SHD code has a verifiable mapping.",
    prospects: "Prospects", prospectList: "Company prospects", prospectSubtitle: "Internal pipeline, kept separate from official market evidence.", importProspects: "Import prospects", importProspectsHelp: "Upload the approved internal CSV. Names and public URLs are processed only for internal work.", chooseProspectFile: "Choose CSV file", importCsv: "Import CSV", importing: "Importing…", totalProspects: "Total prospects", bogotaOnly: "Bogotá only", coverageMap: "Coverage map", coverageMapHelp: "This is not a nationwide coverage map. All recorded prospects are in Bogotá.", bySector: "By sector", byStatus: "By outreach status", company: "Company", publicSource: "Public source", fitSignal: "Fit signal", initialProposal: "Initial proposal", decisionMakerRole: "Decision-maker role", priority: "Priority", outreachStatus: "Outreach status", filters: "Filters", all: "All", clearFilters: "Clear filters", previous: "Previous", next: "Next", noProspects: "No prospects match the selected filters.", importedProspects: "Prospects imported", duplicateProspectImport: "This file was already imported.", invalidProspectCsv: "The CSV is invalid. Check required fields, URLs, and duplicate IDs.", prospectAccessDenied: "You do not have access to company prospects.", prospectImportDenied: "Only administrators can import prospect files.", updateProspect: "Update prospect", saved: "Saved", prospectsNav: "Company prospects",
  },
  es: {
    accessDenied: "Acceso denegado", noRole: "Tu identidad no tiene un rol en la aplicación.", marketExplorer: "Explorador de mercados", noScores: "No hay puntuaciones de mercado con licencia disponibles para esta cuenta.",
    intelligence: "Inteligencia de mercados interna", marketOverview: "Resumen del mercado", subtitle: "Priorizá mercados para una investigación más profunda con evidencia trazable.", city: "Ciudad", pilot: "Piloto · Colombia", language: "Idioma", english: "English", spanish: "Español",
    topOpportunity: "Mayor oportunidad", averageOpportunity: "Oportunidad media", evidenceConfidence: "Confianza de la evidencia", evaluatedSectors: "Sectores evaluados", noScoredSectors: "No hay sectores puntuados", acrossScored: "Entre sectores puntuados", separate: "Independiente de la oportunidad", insufficientData: "con datos insuficientes",
    licensePending: "Revisión de licencia pendiente", syntheticWarning: "Solo muestra sintética. No puede publicarse en vistas de leads accionables ni usarse como evidencia oficial de mercado.", importStatus: "Estado de importación", rowsAccepted: "filas aceptadas", noRecentRun: "No hay ejecuciones recientes", run: "Ejecución",
    signals: "Leé las dos señales de forma independiente", signalsDetail: "La oportunidad expresa prioridad relativa de investigación. La confianza expresa calidad de la evidencia; ninguna es probabilidad de compra ni ingreso esperado.", period: "Periodo", researchPriority: "Prioridad de investigación", sectorRanking: "Ranking de sectores", selectSector: "Seleccioná un sector para inspeccionar la evidencia detrás de su puntuación.", sectors: "sectores", sector: "Sector", opportunity: "Oportunidad", confidence: "Confianza", readyForReview: "Listo para revisión", selectedSector: "Sector seleccionado", factorEvidence: "Evidencia de factores", evidence: "Evidencia", confidenceEvidence: "Evidencia de confianza", evidenceRecords: "Registros de evidencia", openSource: "Abrir fuente", observed: "Observado", license: "licencia", review: "revisión", missing: "Ausente", points: "pts", outOf100: "/ 100", evidencePanel: "Evidencia del sector seleccionado", confidenceModel: "Modelo de confianza", model: "Modelo", home: "Inicio de Neora Labs", footer: "Vista previa sintética de apoyo a decisiones · Las puntuaciones son deterministas, versionadas y no son evidencia de producción.", overview: "Resumen", ranking: "Ranking", navEvidence: "Evidencia", primary: "Principal", selectedEvidence: "Evidencia del sector seleccionado", workspace: "Espacio interno de investigación",
    back: "Volver al explorador", importOfficial: "Importar fuente oficial", importDescription: "Los datos se cargan directamente al almacenamiento privado, se guardan por checksum y pasan a revisión antes de que un worker separado los procese. No se usan para puntuar empresas.", source: "Fuente", requiredCiiu: "CIIU obligatoria", localFile: "Archivo local", version: "Versión", dictionaryLabels: "Etiquetas del diccionario EMICRON (JSON)", dictionaryHelp: "Toda variable Pxxxx usada debe tener su etiqueta oficial; no se interpretan códigos sin ella.", protections: "Protecciones activas", checksum: "SHA-256 calculado en el navegador.", immutablePath: "Ruta raw/sha256/… inmutable.", separateReviewer: "La misma identidad no puede aprobar.", unresolvedMapping: "Datos ICA sin homologación verificable permanecen como evidencia insuficiente.", preparing: "Preparando carga…", uploadReview: "Subir y enviar a revisión", recentRequests: "Solicitudes recientes", noRequests: "Todavía no hay cargas solicitadas.", file: "Archivo", status: "Estado", rule: "Regla", chooseFile: "Elegí un archivo antes de continuar.", invalidJson: "Las etiquetas del diccionario deben ser JSON válido.", uploadPrepareError: "No se pudo preparar la carga", storageMissing: "El almacenamiento S3 no está configurado todavía. No se cargó ningún archivo.", uploadRejected: "La carga directa fue rechazada; el archivo no pasó a revisión.", confirmError: "No se pudo confirmar la carga", received: "Archivo recibido. Quedó pendiente de revisión por una segunda identidad autorizada.", unexpectedError: "Error inesperado", ciiuNotice: "Clasificación obligatoria: Rev. 4 A.C. (2022).", emicronNotice: "EMICRON solo genera evidencia contextual GRUPOS12; no crea puntuaciones por división.", icaNotice: "ICA queda bloqueado hasta homologar cada código SHD de forma verificable.",
    prospects: "Prospectos", prospectList: "Prospectos de empresas", prospectSubtitle: "Pipeline interno, separado de la evidencia oficial de mercado.", importProspects: "Importar prospectos", importProspectsHelp: "Subí el CSV interno aprobado. Los nombres y URLs públicas se procesan solo para trabajo interno.", chooseProspectFile: "Elegí un archivo CSV", importCsv: "Importar CSV", importing: "Importando…", totalProspects: "Prospectos totales", bogotaOnly: "Solo Bogotá", coverageMap: "Mapa de cobertura", coverageMapHelp: "No es un mapa de cobertura nacional. Todos los prospectos registrados están en Bogotá.", bySector: "Por sector", byStatus: "Por estado de contacto", company: "Empresa", publicSource: "Fuente pública", fitSignal: "Señal de encaje", initialProposal: "Propuesta inicial", decisionMakerRole: "Rol del decisor", priority: "Prioridad", outreachStatus: "Estado de contacto", filters: "Filtros", all: "Todos", clearFilters: "Limpiar filtros", previous: "Anterior", next: "Siguiente", noProspects: "No hay prospectos para los filtros seleccionados.", importedProspects: "Prospectos importados", duplicateProspectImport: "Este archivo ya fue importado.", invalidProspectCsv: "El CSV no es válido. Revisá campos obligatorios, URLs e IDs duplicados.", prospectAccessDenied: "No tenés acceso a los prospectos de empresas.", prospectImportDenied: "Solo administradores pueden importar archivos de prospectos.", updateProspect: "Actualizar prospecto", saved: "Guardado", prospectsNav: "Prospectos de empresas",
  },
} as const satisfies Record<Locale, Record<string, string>>;
export type MessageKey = keyof typeof messages.en;
export function isLocale(value: string | null | undefined): value is Locale { return value === "es" || value === "en"; }
export function resolveLocale(input: { accountLocale?: string | null; cookieLocale?: string | null; acceptLanguage?: string | null }): Locale {
  if (isLocale(input.accountLocale)) return input.accountLocale;
  if (isLocale(input.cookieLocale)) return input.cookieLocale;
  return input.acceptLanguage?.toLowerCase().split(",").some((part) => part.trim().startsWith("es")) ? "es" : "en";
}
export function getMessages(locale: Locale) { return messages[locale]; }



